JShantzAssignment4/Models/DbGenerated/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace JShantzAssignment4.Models.DbGenerated
{
    [Table("invoices")]
    [Index(nameof(InvoiceDate), Name = "invoices_invoice_date_ix")]
    public partial class Invoice
    {
        public Invoice()
        {
            InvoiceLineItems = new HashSet<InvoiceLineItem>();
        }

        [Key]
        [Column("invoice_id")]
        public int InvoiceId { get; set; }
        [Column("vendor_id")]
        public int VendorId { get; set; }
        [Required]
        [Column("invoice_number")]
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
        [Column("invoice_date", TypeName = "datetime")]
        public DateTime InvoiceDate { get; set; }
        [Column("invoice_total", TypeName = "decimal(9, 2)")]
        public decimal InvoiceTotal { get; set; }
        [Column("payment_total", TypeName = "decimal(9, 2)")]
        public decimal PaymentTotal { get; set; }
        [Column("credit_total", TypeName = "decimal(9, 2)")]
        public decimal CreditTotal { get; set; }
        [Column("terms_id")]
        public int TermsId { get; set; }
        [Column("invoice_due_date", TypeName = "datetime")]
        public DateTime InvoiceDueDate { get; set; }
        [Column("payment_date", TypeName = "datetime")]
        public DateTime? PaymentDate { get; set; }

        [ForeignKey(nameof(TermsId))]
        [InverseProperty(nameof(Term.Invoices))]
        public virtual Term Terms { get; set; }
        [ForeignKey(nameof(VendorId))]
        [InverseProperty("Invoices")]
        public virtual Vendor Vendor { get; set; }
        [InverseProperty(nameof(InvoiceLineItem.Invoice))]
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
    }
}

JShantzAssignment4/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JShantzAssignment4.Models;
using JShantzAssignment4.Models.DbGenerated;
using Microsoft.EntityFrameworkCore;

namespace JShantzAssignment4.Controllers
{
    public class InvoicesController : Controller
    {
        private apContext _apContext;

        public InvoicesController(apContext apContext)
        {
            _apContext = apContext;
        }

        public IActionResult Index(int vendorId, int invoiceId, string activeCategory)
        {
            var invoices = _apContext.Invoices.Where(i => i.VendorId == vendorId).OrderBy(i => i.InvoiceId).ToList();

            var vendor = _apContext.Vendors.Find(vendorId);

            ViewBag.Vendor = vendor;
            ViewBag.Term = _apContext.Terms.Find(vendor.DefaultTermsId);
            ViewBag.Invoices = invoices;


            if (invoiceId == 0 && invoices.Count() != 0)
            {
                invoiceId = invoices[0].InvoiceId;
            }

            var invoiceLines = _apContext.InvoiceLineItems.Where(il => il.InvoiceId == invoiceId).OrderBy(il => il.InvoiceSequence).ToList();

            ViewData["ActiveCategory"] = activeCategory;
            ViewData["ActiveInvoice"] = invoiceId;
            ViewData["newInvoiceSequence"] = invoiceLines.Count() + 1;
            ViewBag.InvoiceLines = invoiceLines;

            return View(new InvoiceLineItem());
        }

        public IActionResult Add(InvoiceLineItem lineItem, string activeCategory)
        {
            Invoice invoice = _apContext.Invoices.Find(lineItem.InvoiceId);

            invoice.InvoiceTotal += lineItem.LineItemAmount;
            invoice.PaymentTotal += lineItem.LineItemAmount;

            _apContext.InvoiceLineItems.Add(lineItem);
            _apContext.Invoices.Update(invoice);
            _apContext.SaveChanges();

            return RedirectToAction("Index", "Invoices", new { vendorId = invoice.VendorId ,invoiceId = lineItem.InvoiceId, activeCategory = activeCategory});
        }
    }
}

JShantzAssignment4/Controllers/VendorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using JShantzAssignment4.Models.DbGenerated;
using JShantzAssignment4.Models;
using Microsoft.EntityFrameworkCore;

namespace JShantzAssignment4.Controllers
{
    public class VendorsController : Controller
    {
        private apContext _apContext;

        public VendorsController(apContext apContext)
        {
            _apContext = apContext;
        }

        public IActionResult Index(string activeCategory)
        {
            List<Vendor> vendors = new List<Vendor>();
            string[] letters;
            if(activeCategory == "A - E" || activeCategory == null)
            {
                ViewData["ActiveCategory"] = "A - E";
                letters = new string[] { "A", "B", "C", "D", "E" };
            }
            else if(activeCategory == "F - K")
            {
                ViewData["ActiveCategory"] = "F - K";
                letters = new string[] { "F", "G", "H", "I", "J", "K" };
            }
            else if (activeCategory == "L - R")
            {
                ViewData["ActiveCategory"] = "L - R";
                letters = new string[] { "L", "M", "N", "O", "P", "Q", "R" };
            }
            else
            {
                ViewData["ActiveCategory"] = "S - Z";
                letters = new string[] { "S", "T", "U", "V", "W", "X", "Y", "Z" };
            }

            foreach (string letter in letters)
            {
                vendors.AddRange(_apContext.Vendors.Where(v => (v.VendorName.StartsWith(letter))
                    && (v.IsDeleted == false)).OrderBy(v => v.VendorName).ToList());
            }

            return View(vendors);
        }
    }
}

JShantzAssignment4/Views/Invoices/Index.cshtml
@model InvoiceLineItem
@{
    ViewData["Title"] = "Index";
    var vendor = ViewBag.Vendor;
    var baseClassName = "table-nav";
    var activeClassName = " table-nav-active";
    var className = "";
    int activeInvoice = (int)ViewData["ActiveInvoice"];
    string activeInvoiceNumber = "0";
    var invoices = ViewBag.Invoices;
    var invoiceLines = ViewBag.InvoiceLines;
}

<br />
<br />
<div class="row">
    <h2 class="col-sm-9">Invoices for @vendor.VendorName</h2>
    <a asp-controller="Vendors" asp-action="Index" asp-route-activeCategory="@ViewData["ActiveCategory"]" class="col-sm-3">
        Return to @ViewData["ActiveCategory"] Vendors
    </a>
</div>
<br />
<br />
<div class="row">
    <p class="col-sm-10 font-weight-light">Address: @vendor.VendorAddress1 @vendor.VendorAddress2 @vendor.VendorCity</p>
    <p class="col-sm-2 font-weight-light">Terms: @ViewBag.Term.TermsDueDays days</p>
</div>

<div class="row">
    <div class="col-sm-6">
        <p class="font-weight-bold">Invoices:</p>
        @if (invoices.Count != 0)
        {
            <table>
                @foreach (var invoice in invoices)
                {
                    if (activeInvoice == invoice.InvoiceId)
                    {
                        className = baseClassName + activeClassName;
                        activeInvoiceNumber = invoice.InvoiceNumber;
                    }
                    else
                    {
                        className = baseClassName;
                    }
                    <tr>
                        <td>
                            <a class="@className" asp-controller="Invoices" asp-action="Index" asp-route-vendorId="@vendor.VendorId" asp-route-invoiceId="@invoice.InvoiceId" asp-route-activeCategory="@ViewData["ActiveCategory"]">Invoice @invoice.InvoiceNumber</a>
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
    <div class="col-sm-6">
        @if (activeInvoice != 0)
        {
            <p class="font-weight-bold">Line items for Invoice @activeInvoiceNumber</p>
            <br />
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Description</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var lineItem in invoiceLines)
                    {
                        <tr>
                            <td>@lineItem.LineItemDescription</td>
                            <td>$@lineItem.LineItemAmount.ToString()</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        <form asp-controller="Invoices" asp-action="Add" asp-route-vendorId="@vendor.VendorId" asp-route-activeCategory="@ViewData["ActiveCategory"]" >
            <div class="row form-group">
                <div class="col-sm-3">
                    <label>Description:</label>
                </div>
                <div class="col-sm-6">
                    <input type="text" class="form-control" asp-for="LineItemDescription" />
                </div>
            </div>
            <div class="row form-group">
                <div class="col-sm-3"><label>Amount:</label></div>
                <div class="col-sm-3">
                    <input type="number" class="form-control" step="0.01" asp-for="LineItemAmount" placeholder="0.00" />
                </div>
            </div>
            <input type="hidden" asp-for="InvoiceId" value="@activeInvoice" />
            <input type="hidden" asp-for="AccountNumber" value="@vendor.DefaultAccountNumber" />
            <input type="hidden" asp-for="InvoiceSequence" value="@ViewData["newInvoiceSequence"]" />

            <input type="submit" class="btn btn-primary" value="Add new line item" />
        </form>
    </div>


</div>