JShantzAssignment4/Models/DbGenerated/Vendor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace JShantzAssignment4.Models.DbGenerated
{
    [Table("vendors")]
    [Index(nameof(VendorName), Name = "UQ__vendors__6107BA71FF1206B7", IsUnique = true)]
    public partial class Vendor
    {
        public Vendor()
        {
            Invoices = new HashSet<Invoice>();
        }

        [Key]
        [Column("vendor_id")]
        public int VendorId { get; set; }
        [Required]
        [Column("vendor_name")]
        [StringLength(256)]
        public string VendorName { get; set; }
        [Column("vendor_address1")]
        [StringLength(128)]
        public string VendorAddress1 { get; set; }
        [Column("vendor_address2")]
        [StringLength(128)]
        public string VendorAddress2 { get; set; }
        [Required]
        [Column("vendor_city")]
        [StringLength(64)]
        public string VendorCity { get; set; }
        [Required]
        [Column("vendor_state")]
        [StringLength(2)]
        public string VendorState { get; set; }
        [Required]
        [Column("vendor_zip_code")]
        [StringLength(20)]
        public string VendorZipCode { get; set; }
        [Column("vendor_phone")]
        [StringLength(50)]
        public string VendorPhone { get; set; }
        [Column("vendor_contact_last_name")]
        [StringLength(128)]
        public string VendorContactLastName { get; set; }
        [Column("vendor_contact_first_name")]
        [StringLength(128)]
        public string VendorContactFirstName { get; set; }
        [Column("vendor_contact_email")]
        [StringLength(128)]
        public string VendorContactEmail { get; set; }
        [Column("default_terms_id")]
        public int DefaultTermsId { get; set; }
        [Column("default_account_number")]
        public int DefaultAccountNumber { get; set; }
        [Column("is_deleted")]
        public bool IsDeleted { get; set; }

        [ForeignKey(nameof(DefaultAccountNumber))]
        [InverseProperty(nameof(GeneralLedgerAccount.Vendors))]
        public virtual GeneralLedgerAccount DefaultAccountNumberNavigation { get; set; }
        [ForeignKey(nameof(DefaultTermsId))]
        [InverseProperty(nameof(Term.Vendors))]
        public virtual Term DefaultTerms { get; set; }
        [InverseProperty(nameof(Invoice.Vendor))]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

JShantzAssignment4/Models/Vendor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace JShantzAssignment4.Models.DbGenerated
{
    [ModelMetadataType(typeof(VendorMetadata))]
    public partial class Vendor
    {
    }
}

JShantzAssignment4/Controllers/VendorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using JShantzAssignment4.Models;
using JShantzAssignment4.Models.DbGenerated;
using Microsoft.EntityFrameworkCore;

namespace JShantzAssignment4.Controllers
{
    public class VendorController : Controller
    {
        private apContext _apContext;

        public VendorController(apContext apContext)
        {
            _apContext = apContext;
        }

        [HttpGet]
        public IActionResult Add(string activeCategory)
        {
            ViewData["ActiveCategory"] = activeCategory;

            ViewData["Action"] = "Add";

            ViewData["Terms"] = _apContext.Terms.OrderBy(t => t.TermsDueDays).ToList();

            ViewData["Accounts"] = _apContext.GeneralLedgerAccounts.OrderBy(g => g.AccountNumber).ToList();

            return View("Edit", new Vendor());
        }

        [HttpPost]
        public IActionResult Add(Vendor newVendor, string activeCategory)
        {
            if (ModelState.IsValid)
            {
                _apContext.Vendors.Add(newVendor);
                _apContext.SaveChanges();

                return RedirectToAction("Index", "Vendors", new { activeCategory = activeCategory });
            }
            else
            {
                ViewData["ActiveCategory"] = activeCategory;
                ViewData["Action"] = "Add";
                ViewData["Terms"] = _apContext.Terms.OrderBy(t => t.TermsDueDays).ToList();
                ViewData["Accounts"] = _apContext.GeneralLedgerAccounts.OrderBy(g => g.AccountNumber).ToList();
                ModelState.AddModelError("", "There were errors in the fom - please fix them and try again.");
                return View("Edit", newVendor);
            }
        }

        [HttpGet]
        public IActionResult Edit(int vendorId ,string activeCategory)
        {
            ViewData["ActiveCategory"] = activeCategory;
            ViewData["Action"] = "Edit";
            ViewData["Terms"] = _apContext.Terms.OrderBy(t => t.TermsDueDays).ToList();
            ViewData["Accounts"] = _apContext.GeneralLedgerAccounts.OrderBy(g => g.AccountNumber).ToList();

            Vendor vendor = _apContext.Vendors.Find(vendorId);

            return View("Edit", vendor);
        }

        [HttpPost]
        public IActionResult Edit(Vendor vendor, string activeCategory)
        {
            if (ModelState.IsValid)
            {
                _apContext.Vendors.Update(vendor);
                _apContext.SaveChanges();

                return RedirectToAction("Index", "Vendors", new { activeCategory = activeCategory });
            }
            else
            {
                ViewData["ActiveCategory"] = activeCategory;
                ViewData["Action"] = "Edit";
                ViewData["Terms"] = _apContext.Terms.OrderBy(t => t.TermsDueDays).ToList();
                ViewData["Accounts"] = _apContext.GeneralLedgerAccounts.OrderBy(g => g.AccountNumber).ToList();
                ModelState.AddModelError("", "There were errors in the fom - please fix them and try again.");

                return View("Edit", vendor);
            }
        }

        public IActionResult Delete(int vendorId, string activeCategory)
        {
            Vendor vendor = _apContext.Vendors.Find(vendorId);
            vendor.IsDeleted = true;
            _apContext.Vendors.Update(vendor);
            _apContext.SaveChanges();
            TempData["Message"] = vendor.VendorName;
            TempData["vendorId"] = vendor.VendorId;
            return RedirectToAction("Index", "Vendors", new { activeCategory = activeCategory });
        }

        public IActionResult Undo(int vendorId, string activeCategory)
        {
            Vendor vendor = _apContext.Vendors.Find(vendorId);
            vendor.IsDeleted = false;
            _apContext.Vendors.Update(vendor);
            _apContext.SaveChanges();
            return RedirectToAction("Index", "Vendors", new { activeCategory = activeCategory });
        }
    }
}

JShantzAssignment4/Controllers/VendorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using JShantzAssignment4.Models.DbGenerated;
using JShantzAssignment4.Models;
using Microsoft.EntityFrameworkCore;

namespace JShantzAssignment4.Controllers
{
    public class VendorsController : Controller
    {
        private apContext _apContext;

        public VendorsController(apContext apContext)
        {
            _apContext = apContext;
        }

        public IActionResult Index(string activeCategory)
        {
            List<Vendor> vendors = new List<Vendor>();
            string[] letters;
            if(activeCategory == "A - E" || activeCategory == null)
            {
                ViewData["ActiveCategory"] = "A - E";
                letters = new string[] { "A", "B", "C", "D", "E" };
            }
            else if(activeCategory == "F - K")
            {
                ViewData["ActiveCategory"] = "F - K";
                letters = new string[] { "F", "G", "H", "I", "J", "K" };
            }
            else if (activeCategory == "L - R")
            {
                ViewData["ActiveCategory"] = "L - R";
                letters = new string[] { "L", "M", "N", "O", "P", "Q", "R" };
            }
            else
            {
                ViewData["ActiveCategory"] = "S - Z";
                letters = new string[] { "S", "T", "U", "V", "W", "X", "Y", "Z" };
            }

            foreach (string letter in letters)
            {
                vendors.AddRange(_apContext.Vendors.Where(v => (v.VendorName.StartsWith(letter))
                    && (v.IsDeleted == false)).OrderBy(v => v.VendorName).ToList());
            }

            return View(vendors);
        }
    }
}

JShantzAssignment4/Views/Vendors/Index.cshtml
@model List<Vendor>
@{
    ViewData["Title"] = "Index";
    var baseClassName = "nav-link";
    var className = "";
    string actveCategory = (string)ViewData["ActiveCategory"];
}

<br />
<h1>Vendors</h1>
<br /><br />
<div class="row">
    <ul class="nav nav-tabs">
        @if (actveCategory == "A - E")
        {
            className = baseClassName + " active";
        }
        else
        {
            className = baseClassName;
        }
        <li class="nav-item">
            <a class="@className" asp-controller="Vendors" asp-action="Index" asp-route-activeCategory="A - E">A - E</a>
        </li>

        @if (actveCategory == "F - K")
        {
            className = baseClassName + " active";
        }
        else
        {
            className = baseClassName;
        }
        <li class="nav-item">
            <a class="@className" asp-controller="Vendors" asp-action="Index" asp-route-activeCategory="F - K">F - K</a>
        </li>

        @if (actveCategory == "L - R")
        {
            className = baseClassName + " active";
        }
        else
        {
            className = baseClassName;
        }
        <li class="nav-item">
            <a class="@className" asp-controller="Vendors" asp-action="Index" asp-route-activeCategory="L - R">L - R</a>
        </li>

        @if (actveCategory == "S - Z")
        {
            className = baseClassName + " active";
        }
        else
        {
            className = baseClassName;
        }
        <li class="nav-item">
            <a class="@className" asp-controller="Vendors" asp-action="Index" asp-route-activeCategory="S - Z">S - Z</a>
        </li>
    </ul>
</div>
<br />
<div class="row">
    <a asp-controller="Vendor" asp-action="Add" asp-route-activeCategory="@actveCategory" class="col-sm-6">Add new vendor</a>
    @if (TempData.ContainsKey("Message"))
    {
        <p class="col">
            The vendor "@TempData["Message"]" was deleted.
            <a asp-controller="Vendor" asp-action="Undo" asp-route-vendorId="@TempData["vendorId"]" asp-route-activeCategory="@actveCategory">Undo</a> this delete
        </p>
    }
</div>
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var vendor in Model)
        {
            <tr>
                <td>@vendor.VendorName</td>
                <td>@vendor.VendorAddress1 @vendor.VendorCity</td>
                <td>
                    <a asp-controller="Invoices" asp-action="Index" asp-route-vendorId="@vendor.VendorId" asp-route-activeCategory="@actveCategory">Invoices</a>
                    <span>|</span>
                    <a asp-controller="Vendor" asp-action="Edit" asp-route-vendorId="@vendor.VendorId" asp-route-activeCategory="@actveCategory">Edit</a>
                    <span>|</span>
                    <a asp-controller="Vendor" asp-action="Delete" asp-route-vendorId="@vendor.VendorId" asp-route-activeCategory="@actveCategory">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>